# Generated by Django 4.2 on 2024-08-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='measajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_mensaje', models.TextField()),
                ('remitente', models.TextField()),
                ('destinatario', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
